# **1. islem kutuphaneler**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.metrics import confusion_matrix

# **2. veri önişleme**

**2.1 verilerin yüklenmesi**

In [ ]:
veriler = pd.read_csv("veriler.csv")

**test**

In [ ]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [ ]:
x = veriler.iloc[:,1:4].values # bağımsız [5:,1:4] en düzgün çalışan sınıflandırma temizlenmiş veri
y = veriler.iloc[:,4:].values

**verilerin eğitim ve test için bölünmesi**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test ,y_train , y_test = train_test_split(x , y , test_size= 0.33 , random_state = 0)

**verilerin ölçeklenmesi**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

# ***buradan itibaren sınıflandırma algoritmaları başlar***

***1. logistic regression***

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logr = LogisticRegression(random_state=0)

In [ ]:
logr.fit(X_train, y_train) # eğitim

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = logr.predict(X_test) #tahmin
y_pred

array(['e', 'e', 'e', 'e', 'k', 'e', 'e', 'e'], dtype=object)

***karmaşık matrisi***

In [ ]:
cm = confusion_matrix(y_test , y_pred)
cm

array([[0, 1],
       [7, 0]])

# ***k -nn k en yakın komşu***

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5 , metric="minkowski")

In [ ]:
knn.fit(X_train , y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred_knn = knn.predict(x_test)

In [ ]:
cm = confusion_matrix(y_test ,y_pred)
cm

array([[0, 1],
       [7, 0]])

# ***SVC support vector machine***

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc = SVC(kernel="poly")

In [ ]:
svc.fit(x_train ,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svc.predict(x_test)
y_pred

array(['e', 'k', 'e', 'e', 'k', 'e', 'e', 'k'], dtype=object)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 1],
       [5, 2]])