# ***kütüphane***

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 

# ***veri önişleme***

***veri yükleme***

In [3]:
veri = pd.read_csv("odev_veri_kumesi.csv")
veri

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

# ***outlook encoder : kategorik -> numerik***

In [4]:
outlook = veri.iloc[:,:1].values
outlook

array([['sunny'],
       ['sunny'],
       ['overcast'],
       ['rainy'],
       ['rainy'],
       ['rainy'],
       ['overcast'],
       ['sunny'],
       ['sunny'],
       ['rainy'],
       ['sunny'],
       ['overcast'],
       ['overcast'],
       ['rainy']], dtype=object)

In [5]:
from sklearn import preprocessing

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
outlook[:,0] =  le.fit_transform(veri.iloc[:,0])
outlook

array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]], dtype=object)

In [8]:
ohe = preprocessing.OneHotEncoder()
outlook = ohe.fit_transform(outlook).toarray()
outlook

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

***windy encoder***

In [9]:
windy = veri.iloc[:,3:4].values
windy

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [10]:
le = preprocessing.LabelEncoder()

In [11]:
#windy[:,-1] = le.fit_transform(veri.iloc[:,-1])
windy

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [12]:
windy = ohe.fit_transform(windy).toarray()
windy

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

***play encoder***

In [13]:
play = veri.iloc[:,-1:].values
play

array([['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no']], dtype=object)

In [14]:
play[:,-1] = le.fit_transform(veri.iloc[:,-1])
play

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=object)

In [15]:
play = ohe.fit_transform(play).toarray()
play

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

***sıcaklık ve nem encoder***

In [16]:
temp_hum = veri.iloc[:,1:3].values
temp_hum

array([[85, 85],
       [80, 90],
       [83, 86],
       [70, 96],
       [68, 80],
       [65, 70],
       [64, 65],
       [72, 95],
       [69, 70],
       [75, 80],
       [75, 70],
       [72, 90],
       [81, 75],
       [71, 91]])

# ***numpy dizilerini dataframe dönüşümü***

In [17]:
sonuc_o = pd.DataFrame(data= outlook ,index= range(14) ,columns=["sunny","overcast","rainy"])
sonuc_o

sunny  overcast  rainy
0     0.0       0.0    1.0
1     0.0       0.0    1.0
2     1.0       0.0    0.0
3     0.0       1.0    0.0
4     0.0       1.0    0.0
5     0.0       1.0    0.0
6     1.0       0.0    0.0
7     0.0       0.0    1.0
8     0.0       0.0    1.0
9     0.0       1.0    0.0
10    0.0       0.0    1.0
11    1.0       0.0    0.0
12    1.0       0.0    0.0
13    0.0       1.0    0.0

In [18]:
sonuc_w = pd.DataFrame(data=windy[:,:1] , index= range(14), columns=["windy"])
sonuc_w

windy
0     1.0
1     0.0
2     1.0
3     1.0
4     1.0
5     0.0
6     0.0
7     1.0
8     1.0
9     1.0
10    0.0
11    0.0
12    1.0
13    0.0

In [19]:
sonuc_p = pd.DataFrame(data= play[:,:1] , index= range(14), columns=["no"])
sonuc_p

no
0   1.0
1   1.0
2   0.0
3   0.0
4   0.0
5   1.0
6   0.0
7   1.0
8   0.0
9   0.0
10  0.0
11  0.0
12  0.0
13  1.0

In [20]:
sonuc_th = pd.DataFrame(data=temp_hum , index= range(14), columns=["temperature","humidity"])
sonuc_th

temperature  humidity
0            85        85
1            80        90
2            83        86
3            70        96
4            68        80
5            65        70
6            64        65
7            72        95
8            69        70
9            75        80
10           75        70
11           72        90
12           81        75
13           71        91

# ***dataframe birleştirme işlemi***

In [21]:
s = pd.concat([sonuc_o , sonuc_th], axis=1)
s

sunny  overcast  rainy  temperature  humidity
0     0.0       0.0    1.0           85        85
1     0.0       0.0    1.0           80        90
2     1.0       0.0    0.0           83        86
3     0.0       1.0    0.0           70        96
4     0.0       1.0    0.0           68        80
5     0.0       1.0    0.0           65        70
6     1.0       0.0    0.0           64        65
7     0.0       0.0    1.0           72        95
8     0.0       0.0    1.0           69        70
9     0.0       1.0    0.0           75        80
10    0.0       0.0    1.0           75        70
11    1.0       0.0    0.0           72        90
12    1.0       0.0    0.0           81        75
13    0.0       1.0    0.0           71        91

In [22]:
s2 = pd.concat([s , sonuc_w], axis=1)
s2

sunny  overcast  rainy  temperature  humidity  windy
0     0.0       0.0    1.0           85        85    1.0
1     0.0       0.0    1.0           80        90    0.0
2     1.0       0.0    0.0           83        86    1.0
3     0.0       1.0    0.0           70        96    1.0
4     0.0       1.0    0.0           68        80    1.0
5     0.0       1.0    0.0           65        70    0.0
6     1.0       0.0    0.0           64        65    0.0
7     0.0       0.0    1.0           72        95    1.0
8     0.0       0.0    1.0           69        70    1.0
9     0.0       1.0    0.0           75        80    1.0
10    0.0       0.0    1.0           75        70    0.0
11    1.0       0.0    0.0           72        90    0.0
12    1.0       0.0    0.0           81        75    1.0
13    0.0       1.0    0.0           71        91    0.0

In [23]:
s3 = pd.concat([s2 , sonuc_p], axis= 1)
s3

sunny  overcast  rainy  temperature  humidity  windy   no
0     0.0       0.0    1.0           85        85    1.0  1.0
1     0.0       0.0    1.0           80        90    0.0  1.0
2     1.0       0.0    0.0           83        86    1.0  0.0
3     0.0       1.0    0.0           70        96    1.0  0.0
4     0.0       1.0    0.0           68        80    1.0  0.0
5     0.0       1.0    0.0           65        70    0.0  1.0
6     1.0       0.0    0.0           64        65    0.0  0.0
7     0.0       0.0    1.0           72        95    1.0  1.0
8     0.0       0.0    1.0           69        70    1.0  0.0
9     0.0       1.0    0.0           75        80    1.0  0.0
10    0.0       0.0    1.0           75        70    0.0  0.0
11    1.0       0.0    0.0           72        90    0.0  0.0
12    1.0       0.0    0.0           81        75    1.0  0.0
13    0.0       1.0    0.0           71        91    0.0  1.0

# ***verilerin eğitim ve test için bölünmesi***

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train , x_test , y_train , y_test = train_test_split(s2 ,sonuc_p , test_size = 0.33 , random_state = 0 )

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
regressor = LinearRegression()

In [28]:
regressor.fit(x_train , y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
y_pred = regressor.predict(x_test)
y_pred

array([[0.25766369],
       [0.24628012],
       [0.21001443],
       [0.72818771],
       [0.21427549]])