# ***1. kütüphaneler***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ***2. veri önişleme***

 ***2.1. veri yükleme***

In [ ]:
veriler = pd.read_csv("veriler.csv")

***test***

In [ ]:
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

***encoder : kategorik -> numeric***

In [ ]:
ulke = veriler.iloc[:,0:1].values
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [ ]:
from sklearn import preprocessing

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [ ]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

***encoder : kategorik -> numeric***

In [ ]:
c = veriler.iloc[:,-1:].values
c

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
c[:,-1] = le.fit_transform(veriler.iloc[:,-1])
c

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=object)

In [ ]:
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
c

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

***encoder : kateogorik -> numeric***

In [ ]:
Yas = veriler.iloc[:,1:4].values
Yas

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]])

In [ ]:
le = preprocessing.LabelEncoder()

Yas = le.fit_transform(veriler.iloc[:,-2:-1])

Yas

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 1,  2,  1,  0,  3, 10,  6, 13,  4, 12,  7, 17, 14, 15, 19, 18,  5,
        7,  8,  9, 11, 16])

***numpy dizileri dataframe donusumu***

In [ ]:
sonuc = pd.DataFrame(data = ulke ,index = range(22), columns= ["fr","tr","us"])
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [ ]:
sonuc2 = pd.DataFrame(data= Yas , index= range(22) , columns=["boy","kilo","yas"])
sonuc2

ValueError: ignored

In [ ]:
cinsiyet = veriler.iloc[:,-1].values
cinsiyet

In [ ]:
sonuc3 = pd.DataFrame(data= c [:,:1] , index= range(22) , columns= ["cinsiyet"] )
sonuc3

 ***dataframe birleştirme işlemi***

In [ ]:
s = pd.concat([sonuc, sonuc2], axis=1)
s

In [ ]:
s2 = pd.concat([s ,sonuc3] , axis= 1)
s2

***verilerin eğitim ve test için bölünmesi***

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(s ,sonuc3 , test_size = 0.33 , random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
regressor = LinearRegression()

In [ ]:
regressor.fit(x_train, y_train) 

In [ ]:
y_pred = regressor.predict(x_test)
y_pred

In [ ]:
boy = s2.iloc[:,3:4].values
boy

In [ ]:
sol= s2.iloc[:,:3]
sag = s2.iloc[:,4:]
sag ,sol

In [ ]:
veri = pd.concat([sol , sag] ,axis=1)
veri

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(veri , boy , test_size = 0.33 , random_state = 0)

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
r2 = LinearRegression()
r2.fit(x_train, y_train)

In [ ]:
y_pred= regressor.predict(x_test)
y_pred

In [ ]:
y_test

In [ ]:
import statsmodels.api as sm

In [ ]:
X = np.append(arr = np.ones((22,1)).astype(int) ,values=veri , axis=1)
X

# ***p değeri***

In [ ]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l , dtype=float)
model = sm.OLS(boy , X_l).fit()
model.summary()

In [ ]:
X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l , dtype=float)
model = sm.OLS(boy , X_l).fit()
model.summary()